### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by anselparsa** [mohammadnedaei/BimeYaran-React-MySQL#1]
hi. i run the server and client and the local host is working. but as soon as i click a button in the site like login or sing in the nodemon just showing crash. whats the problem?

**Comment by mohammadnedaei** [comment]
Hey there Parsa!
I'm glad to help you about this issue!
Please send the crash report or error log here!
Also make sure that database is connected properly.
You may find console errors in Chrome Dev Tools too.
@anselparsa

**Comment by anselparsa** [comment]
i have this error in terminal wich server is running:
E:\BIMEH\BimeYaran-React-MySQL-main\server\index.js:69
        if(result.length > 0) {
                  ^

TypeError: Cannot read properties of undefined (reading 'length')
    at Query.<anonymous> (E:\BIMEH\BimeYaran-React-MySQL-main\server\index.js:69:19)
    at Query.<anonymous> (E:\BIMEH\BimeYaran-React-MySQL-main\server\node_modules\mysql\lib\Connection.js:526:10)
    at Query._callback (E:\BIMEH\BimeYaran-React-MySQL-main\server\node_modules\mysql\lib\Connection.js:488:16)
    at Sequence.end (E:\BIMEH\BimeYaran-React-MySQL-main\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at E:\BIMEH\BimeYaran-React-MySQL-main\server\node_modules\mysql\lib\protocol\Protocol.js:404:18
    at Array.forEach (<anonymous>)
    at E:\BIMEH\BimeYaran-React-MySQL-main\server\node_modules\mysql\lib\protocol\Protocol.js:403:13
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v22.2.0
[nodemon] app crashed - waiting for file changes before starting...



and this is error in console of chrome:
SignIn.jsx:25 
 POST http://localhost:3001/check-email net::ERR_CONNECTION_REFUSED
axios.js?v=04114ab6:1447 Uncaught (in promise) 
AxiosError {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: XMLHttpRequest, …}

@mohammadnedaei

**Comment by mohammadnedaei** [comment]
Ok, are you sure the database is connected properly? sounds like in any case, the result in index.js:69 is undefined.
you may console log the err provided by mysql query before line 69 just like below:
`app.post("/check-email", (req, res) => {
    const email = req.body.email;
    con.query("SELECT * FROM users WHERE email = ? ",[email], (err, result) => {
        console.log(err);
    })
})
`

@anselparsa
